### ISSUE TITLE
请问一下包协议的长度选项应该使用哪一个？

### ISSUE THREAD

**Issue by Coolkkmeat** [jiusetian/EasySocket#10]
刚学Socket，用的是Swoole框架，看不太懂。只知道是4字节的int，望指导。
![image](https://user-images.githubusercontent.com/36995273/85406919-1547c100-b595-11ea-8b39-e12bbdb751ee.png)

**Comment by Coolkkmeat** [comment]
服务端给客户端发消息成功了，代码为`pack("N", strlen($data)) . $data`

有另一个问题：
upString是不是没有用此格式，一旦设置服务端解析就会报错。如果确实用了的话，那可能我选的N模式不对，或者配置项不太对。
不明白。
![image](https://user-images.githubusercontent.com/36995273/85412271-fb5dac80-b59b-11ea-9564-060bf856881d.png)

**Comment by jiusetian** [comment]
不太明白你的问题，消息格式统一为header+body，header保存body的长度，body保存消息内容，这个消息格式是服务端和客户端统一的

**Comment by Coolkkmeat** [comment]
调试的时候发现了一个问题，在服务端主动关闭链接之后，会不停的刷log：
```
ork.EasyReader$1.run(EasyReader.java:187)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:196)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:88)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:187)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:196)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:88)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:187)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:196)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:88)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:187)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:196)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:88)
2020-06-23 23:34:55.720 28946-28990/net.coolkk.test W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:187)
无限循环
```
