### ISSUE TITLE
服务端如果突然断开连接，客户端inputStream会NullPointerException导致程序崩溃

### ISSUE THREAD

**Issue by BestDreams** [jiusetian/EasySocket#15]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
        at com.easysocket.connection.iowork.EasyReader.readOriginDataFromSteam(EasyReader.java:217)
        at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:66)
        at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:194)
        at java.lang.Thread.run(Thread.java:761)

**Comment by hu1095878620** [comment]
出现了同样的问题
