### ISSUE TITLE
大神，我问下，我问下我结束socket的时候出现这个异常怎么处理？

### ISSUE THREAD

**Issue by zhoudong850** [jiusetian/EasySocket#23]
![image](https://user-images.githubusercontent.com/16330404/104395034-cc804580-5582-11eb-90ce-48e33131b3d1.png)
我在接收到数据后，结束socket，但是报了错误，我应该怎么正确的结束，而不会出现异常。谢谢

**Comment by jiusetian** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/16330404/104395203-2ed94600-5583-11eb-802b-fddbd9af2cb7.png)
> 
> 我在接收到数据后，结束socket，但是报了错误，我应该怎么正确的结束，而不会出现异常。谢谢
> 
> EasySocket.getInstance().disconnect(false);
> EasySocket.getInstance().destroyConnection();
> 
> W/System.err: java.lang.InterruptedException
> W/System.err: java.net.SocketException: Socket closed
> W/System.err: at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:1991)
> at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2025)
> at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:460)
> W/System.err: at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:649)
> at com.easysocket.connection.iowork.EasyWriter$1.run(EasyWriter.java:82)
> at java.lang.Thread.run(Thread.java:818)
> W/System.err: at libcore.io.Posix.recvfromBytes(Native Method)
> W/System.err: at libcore.io.Posix.recvfrom(Posix.java:185)
> at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
> at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
> at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
> at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
> at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
> at java.io.InputStream.read(InputStream.java:162)
> at com.easysocket.connection.iowork.EasyReader.readOriginDataFromSteam(EasyReader.java:226)
> at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:70)
> at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:188)
> at java.lang.Thread.run(Thread.java:818)
> I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$DisconnectThread run():197 ---> 关闭socket连接
> W/System.err: java.lang.InterruptedException

你断开socket连接，io流读写那里肯定会有异常抛出的，这是正常现象，不影响你程序的运行
