### ISSUE TITLE
大佬，关于服务器接受消息再发送给客户端回执消息问题

### ISSUE THREAD

**Issue by lixiongh-hou** [jiusetian/EasySocket#41]
`System.out: 连接成功
I/com.hl7.test1: ProcessProfilingInfo new_methods=1101 is saved saved_to_disk=1 resolve_classes_delay=8000
I/System.out: easysocket：com.easysocket.connection.iowork.EasyWriter write():95 Socket发送数据String-->MSH|^~\&|TestSendingSystem||||20220519113025.278+0800||ADT^A01^ADT_A01|1|P|2.4|123PID|||123456||Li^Eason||19581221|M|||Nanyuan Street, Nanyuan District 1, Room 101, Unit 2, Crash 2^^Zhejiang^Hangzhou^55175^CHN||(416)888-8888^^PH^^^^18720461606PV1||O|^^^0305^Nephrology Clinic||||||001287||||||||||5407031|||||||||||||||||||||||||20201207093847 
I/System.out: easysocket：com.easysocket.connection.iowork.EasyWriter write():96 Socket发送数据byte[]-->[77, 83, 72, 124, 94, 126, 92, 38, 124, 84, 101, 115, 116, 83, 101, 110, 100, 105, 110, 103, 83, 121, 115, 116, 101, 109, 124, 124, 124, 124, 50, 48, 50, 50, 48, 53, 49, 57, 49, 49, 51, 48, 50, 53, 46, 50, 55, 56, 43, 48, 56, 48, 48, 124, 124, 65, 68, 84, 94, 65, 48, 49, 94, 65, 68, 84, 95, 65, 48, 49, 124, 49, 124, 80, 124, 50, 46, 52, 124, 49, 50, 51, 13, 80, 73, 68, 124, 124, 124, 49, 50, 51, 52, 53, 54, 124, 124, 76, 105, 94, 69, 97, 115, 111, 110, 124, 124, 49, 57, 53, 56, 49, 50, 50, 49, 124, 77, 124, 124, 124, 78, 97, 110, 121, 117, 97, 110, 32, 83, 116, 114, 101, 101, 116, 44, 32, 78, 97, 110, 121, 117, 97, 110, 32, 68, 105, 115, 116, 114, 105, 99, 116, 32, 49, 44, 32, 82, 111, 111, 109, 32, 49, 48, 49, 44, 32, 85, 110, 105, 116, 32, 50, 44, 32, 67, 114, 97, 115, 104, 32, 50, 94, 94, 90, 104, 101, 106, 105, 97, 110, 103, 94, 72, 97, 110, 103, 122, 104, 111, 117, 94, 53, 53, 49, 55, 53, 94, 67, 72, 78, 124, 124, 40, 52, 49, 54, 41, 56, 56, 56, 45, 56, 56, 56, 56, 94, 94, 80, 72, 94, 94, 94, 94, 49, 56, 55, 50, 48, 52, 54, 49, 54, 48, 54, 13, 80, 86, 49, 124, 124, 79, 124, 94, 94, 94, 48, 51, 48, 53, 94, 78, 101, 112, 104, 114, 111, 108, 111, 103, 121, 32, 67, 108, 105, 110, 105, 99, 124, 124, 124, 124, 124, 124, 48, 48, 49, 50, 56, 55, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 53, 52, 48, 55, 48, 51, 49, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 50, 48, 50, 48, 49, 50, 48, 55, 48, 57, 51, 56, 52, 55] 
I/System.out: easysocket：com.easysocket.connection.iowork.EasyReader readOriginDataFromSteam():234 Socket收到数据-->服务端已成功接收文件. 
W/System.err: com.easysocket.exception.ReadRecoverableExeption: 读数据失败，可能因为socket跟服务器断开了连接
W/System.err:     at com.easysocket.connection.iowork.EasyReader.readOriginDataFromSteam(EasyReader.java:228)
W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:70)
W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:188)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
I/System.out: socket监听器收到数据=服务端已成功接收文件.
W/System.err: java.lang.InterruptedException
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
W/System.err:     at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
W/System.err:     at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
W/System.err:     at com.easysocket.connection.iowork.EasyWriter$1.run(EasyWriter.java:83)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
W/System.err: java.lang.InterruptedException
I/System.out: easysocket：com.easysocket.connection.connect.SuperConnection$DisconnectThread run():203 ---> 关闭socket连接 
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
W/System.err:     at java.util.concurrent.DelayQueue.take(DelayQueue.java:216)
W/System.err:     at com.easysocket.connection.dispatcher.CallbackResponseDispatcher$1.run(CallbackResponseDispatcher.java:79)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
I/System.out: easysocket：com.easysocket.connection.reconnect.DefaultReConnection reconnect():80 重连间隔时间-->7523.294324757597 
I/System.out: 断开连接`
大佬，请问这个是什么问题啊

**Comment by zhongdevin** [comment]
解决了吗，是不是收到数据，马上又发数据给服务器
