### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.join()' on a null object reference

### ISSUE THREAD

**Issue by KateJun** [jiusetian/EasySocket#45]
v2.1.1
![image](https://user-images.githubusercontent.com/6227218/234248934-f377f0dc-5654-4243-9aae-6267d5014809.png)
一直开着，时间久了会报错
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.join()' on a null object reference
        at com.easysocket.connection.iowork.EasyWriter.shutDownThread(EasyWriter.java:142)
        at com.easysocket.connection.iowork.EasyWriter.closeWriter(EasyWriter.java:130)
        at com.easysocket.connection.iowork.IOManager.closeIO(IOManager.java:65)
        at com.easysocket.connection.connect.SuperConnection$DisconnectThread.run(SuperConnection.java:192)

**Comment by KateJun** [comment]
![image](https://user-images.githubusercontent.com/6227218/234249430-6d1fc296-ada4-4534-8e9a-a5d48f97589b.png)

**Comment by KateJun** [comment]
![企业微信截图_16838577148621](https://github.com/jiusetian/EasySocket/assets/6227218/046ced85-a09d-4a12-8935-62c50a1eddfb)
![企业微信截图_16838577242301](https://github.com/jiusetian/EasySocket/assets/6227218/e9e8c24c-9b30-47b6-b805-c9ebe39047b2)
断开重连内存一直增加
