### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by showdy** [jiusetian/EasySocket#5]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.concurrent.ExecutorService.isShutdown()' on a null object reference
	at com.easysocket.connection.dispatcher.ResponseDispatcher$1.run(ResponseDispatcher.java:91)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

**Comment by jiusetian** [comment]
是那个timeoutExecutor没有做非空判断，这个bug已经修复了

**Comment by showdy** [comment]
在连接成功后的回调中发送消息，无效！发不出去。。。

**Comment by jiusetian** [comment]
> 在连接成功后的回调中发送消息，无效！发不出去。。。

为什么发不出去，有什么log吗

**Comment by showdy** [comment]
我这边用个延时操作，发送消息就可以了，如果在连接成功的回调中，立即发送消息，会发不出去。

**Comment by jiusetian** [comment]
你确定执行了发送消息吗，发送消息那里的log有打印吗，我这里有个打印的： LogUtil.d("发送数据=" + new String(sendBytes, Charset.forName("utf-8")));

**Comment by showdy** [comment]
是的，日志并没有打印，我试过很多次，不过加一个延时发送的命令的操作就可以了

**Comment by jiusetian** [comment]
但我测试是可以立即发送出去的

**Comment by jambestwick** [comment]
是不是read的时候没捕获，抛到上层了，直接crash了
