### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by showdy** [jiusetian/EasySocket#8]
W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:88)
W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:186)
W/System.err:     at java.lang.Thread.run(Thread.java:784)
W/System.err: java.net.SocketException: Connection reset
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:157)
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:144)
W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:130)
W/System.err:     at com.easysocket.connection.iowork.EasyReader.readHeaderFromSteam(EasyReader.java:195)
W/System.err:     at com.easysocket.connection.iowork.EasyReader.read(EasyReader.java:88)
W/System.err:     at com.easysocket.connection.iowork.EasyReader$1.run(EasyReader.java:186)
W/System.err:     at java.lang.Thread.run(Thread.java:784)

**Comment by jiusetian** [comment]
程序崩了吗

**Comment by showdy** [comment]
那到没有，只是一直收到不到数据，然后刷屏错误日志，断开的连接的也没有回调

**Comment by jiusetian** [comment]
你这个是因为socket断开连接了，是你自己将socket连接断开的吧

**Comment by showdy** [comment]
并没有主动断开，可能就是自己断开了

**Comment by jiusetian** [comment]
按理来说有什么异常情况自己断开会自动重连的
